### PR TITLE
added net-tools to debian-based install command

### PR DESCRIPTION
**Pull request by Kortho**
needed to run the netstat command

### CODE REVIEW

**Comment by SteveClement** [comment]
Which command was missing?

**Comment by Kortho** [comment]
netstat is used in the start_all.sh
and is not always included in the OS (ubuntu  19.04 for instance)
therefor an install of net-tools includes this command

**Comment by Kortho** [comment]
"netstat -an |grep LISTEN |grep 6250 |grep -v tcp6 ; check_redis_port=$?
netstat -an |grep LISTEN |grep 8001 |grep -v tcp6 ; check_dashboard_port=$?"

These does not work without net-tools installed :)

**Comment by SteveClement** [comment]
Cool makes sense

**Comment by mokaddem** [comment]
Thanks a lot!

**Pull request merged**
